config:
  name: ewalletconfig-hs 설정입니다
token:
  expiration_time: 950108 #300000 # 5분
  secret: user_token_hs

gateway:
  ip: 192.168.61.252

ip:
  eureka: http://192.168.61.252:8761/eureka
  hostname: 192.168.61.252
  gateway: 192.168.61.252



